AlShifa_Task/Controllers/InvoiceController.cs
using AlShifa_Task.BLL;
using AlShifa_Task.DAL;
using AlShifa_Task.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace AlShifa_Task.Controllers
{
 
    public class InvoiceController : Controller
    {
        private readonly ApplicationDBContext _context;

        public InvoiceController()
        {
            _context = new ApplicationDBContext();
        }


        /// <summary>
        /// TO get all Invoices
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var invoices = _context.Invoices
                .Include(i => i.Vendor)
                .Include(i => i.InvoiceItems)
                .Include("InvoiceItems.Item")
                .ToList();

            return View(invoices);
        }

        public ActionResult Preview(int id)
        {
            var invoice = _context.Invoices.Include(i => i.Vendor)
                .Include(i => i.InvoiceItems)
                .Include("InvoiceItems.Item")
                .FirstOrDefault(i => i.InvoiceId == id);

            if(invoice ==null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // GET: Invoice/Create
        public ActionResult Create()
        {
            ViewBag.Vendors = new SelectList(_context.Vendors, "VendorId", "Name");//_context.Vendors.ToList();
            ViewBag.Items = _context.Items.ToList();


            return View();
        }

        //// POST: Invoice/Create (Save Invoice)
        //[HttpPost]
        //public ActionResult Create(Invoice invoice, List<int> itemIds, List<int> quantities)
        //{
        //    if (invoice.VendorId == 0 || itemIds == null || quantities == null)
        //    {
        //        ViewBag.Vendors = _context.Vendors.ToList();
        //        ViewBag.Items = _context.Items.ToList();
        //        ViewBag.ErrorMessage = "Please select a vendor and at least one item.";
        //        return View(invoice);
        //    }

        //    // Create invoice record
        //    invoice.Date = DateTime.Now;
        //    invoice.InvoiceItems = new List<InvoiceItem>();

        //    decimal grossTotal = 0;

        //    for (int i = 0; i < itemIds.Count; i++)
        //    {
        //        var item = _context.Items.Find(itemIds[i]);
        //        if (item != null)
        //        {
        //            var totalPrice = item.Price * quantities[i];
        //            grossTotal += totalPrice;

        //            var invoiceItem = new InvoiceItem
        //            {
        //                ItemId = itemIds[i],
        //                Quantity = quantities[i],
        //                TotalPrice = totalPrice
        //            };
        //            invoice.InvoiceItems.Add(invoiceItem);

        //            // Deduct stock quantity
        //            item.QuantityInStock -= quantities[i];
        //        }
        //    }

        //    invoice.GrossTotal = grossTotal;
        //    _context.Invoices.Add(invoice);
        //    _context.SaveChanges();

        //    TempData["SuccessMessage"] = "Invoice created successfully!";
        //    return RedirectToAction("Index", "Item");
        //}

        // POST: Invoice/Create (Save Invoice)
        [HttpPost]
        public JsonResult Create(Invoice invoiceDto)
        {
            try
            {
                
                if (invoiceDto == null || invoiceDto.InvoiceItems == null || !invoiceDto.InvoiceItems.Any())
                {
                    return Json(new { success = false, message = "Invoice must have items!" });
                }

                // Create new Invoice
                var invoice = new Invoice
                {
                    Date = DateTime.Now,
                    VendorId = invoiceDto.VendorId,
                    GrossTotal = invoiceDto.InvoiceItems.Sum(i => i.TotalPrice),
                    InvoiceItems = new List<InvoiceItem>()
                };

                foreach (var item in invoiceDto.InvoiceItems)
                {
                    var dbItem = _context.Items.Find(item.ItemId);
                    if (dbItem == null || dbItem.QuantityInStock < item.Quantity)
                    {
                        return Json(new { success = false, message = $"Insufficient stock for item ID {item.ItemId}!" });
                    }

                    // Deduct stock
                    dbItem.QuantityInStock -= item.Quantity;

                    // Add invoice item
                    invoice.InvoiceItems.Add(new InvoiceItem
                    {
                        ItemId = item.ItemId,
                        Quantity = item.Quantity,
                        TotalPrice = item.TotalPrice
                    });
                }

                // Save to database
                _context.Invoices.Add(invoice);
                _context.SaveChanges();

                return Json(new { success = true, message = "Invoice created successfully!" , invoiceId = invoice.InvoiceId });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Error: " + ex.Message });
            }
        }
    }

}

AlShifa_Task/Controllers/ItemController.cs
using AlShifa_Task.BLL;
using AlShifa_Task.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlShifa_Task.Controllers
{
   
    public class ItemController : Controller
    {
        private readonly ItemService _itemService;

        public ItemController()
        {
            _itemService = new ItemService();
        }

        /// <summary>
        /// TO get all items
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var items = _itemService.GetAllItems();
            return View(items);
        }
        public ActionResult Edit(int id)
        {
            var item = _itemService.GetItemById(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Item item)
        {
            if (ModelState.IsValid)
            {
                bool updated = _itemService.EditStock(item);
                if(updated)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "Unable to update item");
                
            }
            return View(item);
        }
        //Get : item/Delete/id
        public ActionResult Delete(int id)
        {
            var item = _itemService.GetItemById(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Item model)
        {
            bool deleted = _itemService.DeleteStock(model.ItemId);
            if (deleted)
            {
                return RedirectToAction("Index");
            }
            return HttpNotFound();
        }
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// TO create or add new items
        /// </summary>
        /// <param name="item"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(Item item)
        {
            if (ModelState.IsValid)
            {
                _itemService.AddItem(item);
                return RedirectToAction("Index");
            }
            return View(item);
        }
    }

}

AlShifa_Task/Views/Item/Create.cshtml
@model AlShifa_Task.Models.Item

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityInStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityInStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantityInStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AlShifa_Task/Views/Item/Delete.cshtml
@model AlShifa_Task.Models.Item

@{
    ViewBag.Title = "Delete Item";
}

<h2>Delete Item</h2>

<h4>Are you sure you want to delete this?</h4>
<hr />

<dl class="dl-horizontal">
    <dt>Name</dt>
    <dd>@Model.Name</dd>

    <dt>Price</dt>
    <dd>@Model.Price</dd>

    <dt>Quantity In Stock</dt>
    <dd>@Model.QuantityInStock</dd>
</dl>

@using (Html.BeginForm("DeleteConfirmed", "Item", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ItemId)
    
    <div class="form-group">
        <input type="submit" value="Delete" class="btn btn-danger" />
        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
    </div>
}

AlShifa_Task/Views/Item/Edit.cshtml
@model AlShifa_Task.Models.Item

@{
    ViewBag.Title = "Edit Item";
}

<h2>Edit Item</h2>

@using (Html.BeginForm("Edit", "Item", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.ItemId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Price, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityInStock, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.QuantityInStock, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QuantityInStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Changes" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}

AlShifa_Task/Views/Item/Index.cshtml
@model IEnumerable<AlShifa_Task.Models.Item>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create"  ,null, new { @class = " btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuantityInStock)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuantityInStock)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ItemId },new { @class = "btn btn-warning" }) |
                
                @Html.ActionLink("Delete", "Delete", new { id = item.ItemId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

<p>
    Create Order @Html.ActionLink("Order", "Create", "Invoice", null, new {@class = " btn btn-danger"})
</p>
@*<a href="@Url.Action("Preview", "Invoice", new { id = invoice.InvoiceId })" class="btn btn-info">View</a>*@